### ISSUE TITLE
working in 2018?

### ISSUE THREAD

**Issue by kiquenet** [CodeBlueDev/PluralSightDownloader#1]
code ?
http://downloads.codecoding.com/pluralsightdownloader_/publish.htm

blocked
Repository unavailable due to DMCA takedown
 https://github.com/Ebram-Tharwat/CSharp-Pluralsight-Downloader

**Comment by CodeBlueDev** [comment]
This runs on a completely different stack than Ebram's. His was a web application running on asp.net mvc while this project is a windows forms application. No, this does not work in it's current state - but is easily updated to work again. PluralSight removed one URL and changed the structure for their JSON on others.
